config/routes.rb
Rails.application.routes.draw do

  root 'weezy#index'

  get '/weezults', to: "weezy#show", as: 'weezy'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weezy_controller.rb
class WeezyController < ApplicationController
  helper WeezyHelper

  def show
    artist = WeezyHelper::Artist.new("http://www.azlyrics.com/l/lilwayne.html")
    links = artist.extract_links
    @song = WeezyHelper::Song.new(links.sample)

    while !@song && !links.empty?
      @song = WeezyHelper::Song.new(links.sample)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weezy_helper.rb
module WeezyHelper
  class Artist
    attr_reader :noko_doc

    def initialize(link)
      @noko_doc = Nokogiri::HTML(RestClient.get(link, user_agent: "Chrome"))
    end

    def extract_links
      links = []

      noko_doc.css("div#listAlbum > a").each do |item|
        links << "http://azlyrics.com/#{item.attr("href")[3..-1]}"
      end

      links
    end
  end

  class Song
    attr_reader :song_doc

    def initialize(link)
      @song_doc = Nokogiri::HTML(RestClient.get(link, user_agent: "Chrome"))
    end

    def lyrics
      items = []
      items << song_doc.css("div#main b")
      if song_doc.css("span.feat")
        items << song_doc.css("span.feat")
      end
      items << song_doc.css("div[style='margin-left:10px;margin-right:10px;']")
      return items
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeezyGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/weezy/index.html.erb
<div class="home">
  <h1 class="text-center">Random Weezy Generator!</h1>
  <h4 class="text-center">Click the button to randomly generate the lyrics to your favorite Lil' Wayne beats:</h4>

  <%= link_to "Excellent Beat Lyrics", weezy_path, class: "btn btn-primary btn-lg center-block" %>
</div>

app/views/weezy/show.html.erb
<%= link_to "Next Song", weezy_path, class: "btn btn-primary col-xs-4 col-xs-offset-4" %>

<div class="content text-center">
  <%= raw @song.lyrics.first %>
  <%= raw @song.lyrics[1] %>
  <%= raw @song.lyrics.last %>
</div>